import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>
          Rahul Dogra • Modern Software Engineering & Game Development
        </title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex flex-col items-center justify-center w-screen h-screen p-4'>
        <h2 className='text-[3rem] lg:text-[5rem] md:text-[5rem] font-extrabold text-gray-700'>
          Rahul <span className='text-purple-300'>Dogra</span>
        </h2>
        <p className='text-2xl text-gray-700'>
          Full Stack Developer | Game Developer
        </p>
        <p className='text-center text-red-700 text-1xl'>
          Disclaimer: Website is in early development and final website could be
          entirely different.
        </p>
        <p className='text-red-700 text-1xl'>
          Until then checkout my other profiles. 🙏
        </p>
        <div className='grid w-full grid-cols-1 grid-rows-3 gap-3 pt-3 mt-3 lg:grid-rows-1 md:grid-rows-1 lg:grid-cols-3 md:grid-cols-3 lg:w-2/3 md:w-full'>
          <div className='flex flex-col items-center justify-center w-full h-full p-6 text-center duration-500 border-2 border-gray-500 rounded shadow-xl cursor-pointer hover:scale-105'>
            <h2 className='text-lg text-gray-700'>LinkenIn</h2>
            <p className='text-sm text-gray-600'>
              Primarily using for professional networking and showcasing career
              path.
            </p>
            <a
              className='mt-3 text-sm underline cursor-pointer text-violet-500 decoration-dotted underline-offset-2'
              href='https://www.linkedin.com/in/irahuldogra/'
              target='_blank'
              rel='noreferrer'
            >
              Profile
            </a>
          </div>
          <div className='flex flex-col items-center justify-center w-full h-full p-6 text-center duration-500 border-2 border-gray-500 rounded shadow-xl cursor-pointer hover:scale-105'>
            <h2 className='text-lg text-gray-700'>Github</h2>
            <p className='text-sm text-gray-600'>
              Checkout my project contributions on github.
            </p>
            <a
              className='mt-3 text-sm underline cursor-pointer text-violet-500 decoration-dotted underline-offset-2'
              href='https://github.com/deatryde'
              target='_blank'
              rel='noreferrer'
            >
              Profile
            </a>
          </div>
          <div className='flex flex-col items-center justify-center w-full h-full p-6 text-center duration-500 border-2 border-gray-500 rounded shadow-xl cursor-pointer hover:scale-105'>
            <h2 className='text-lg text-gray-700'>Twitter</h2>
            <p className='text-sm text-gray-600'>
              Using for social networking, development, and memes. 😛
            </p>
            <a
              className='mt-3 text-sm underline cursor-pointer text-violet-500 decoration-dotted underline-offset-2'
              href='https://twitter.com/deatryde'
              target='_blank'
              rel='noreferrer'
            >
              Profile
            </a>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
